## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import dataframe_image as dfi

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")

city_data_df.head()
city_data_df.set_index('City_ID')

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
City_ID,,,,,,,,,
0,Ixtapa,20.7000,-105.2000,75.22,89,100,5.01,MX,2022-01-19 23:50:07
1,Karaton,-6.3424,106.1045,79.95,93,97,5.17,ID,2022-01-19 23:50:07
2,Ushuaia,-54.8000,-68.3000,53.26,58,0,17.27,AR,2022-01-19 23:45:13
3,Busselton,-33.6500,115.3333,78.04,52,2,9.98,AU,2022-01-19 23:50:08
4,Pacific Grove,36.6177,-121.9166,65.43,75,0,1.01,US,2022-01-19 23:50:08
...,...,...,...,...,...,...,...,...,...
711,Mount Isa,-20.7333,139.5000,78.57,89,40,4.61,AU,2022-01-20 00:07:54
712,Muros,42.7762,-9.0603,51.24,85,2,9.80,ES,2022-01-20 00:07:54
713,Grand-Santi,4.2500,-54.3833,72.34,99,73,2.48,GF,2022-01-20 00:07:54
714,Daru,-9.0763,143.2092,78.58,89,95,7.90,PG,2022-01-20 00:07:55
715,Maumere,-8.6199,122.2111,77.79,85,100,5.68,ID,2022-01-20 00:07:55

In [3]:
def get_minmax_temp():
    # 2. Prompt the user to enter minimum and maximum temperature criteria 
    min_temp = float(input("What is the minimum temperature you would like for your trip? "))
    max_temp = float(input("What is the maximum temperature you would like for your trip? "))
    return (min_temp, max_temp)

In [4]:
user_input = get_minmax_temp()

What is the minimum temperature you would like for your trip? 0
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= user_input[1]) & \
                                       (city_data_df["Max Temp"] >= user_input[0])]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Ixtapa,20.7000,-105.2000,75.22,89,100,5.01,MX,2022-01-19 23:50:07
1,1,Karaton,-6.3424,106.1045,79.95,93,97,5.17,ID,2022-01-19 23:50:07
2,2,Ushuaia,-54.8000,-68.3000,53.26,58,0,17.27,AR,2022-01-19 23:45:13
3,3,Busselton,-33.6500,115.3333,78.04,52,2,9.98,AU,2022-01-19 23:50:08
4,4,Pacific Grove,36.6177,-121.9166,65.43,75,0,1.01,US,2022-01-19 23:50:08
5,5,Venado Tuerto,-33.7456,-61.9688,76.78,83,98,2.55,AR,2022-01-19 23:50:08
6,6,Bredasdorp,-34.5322,20.0403,66.27,88,27,6.91,ZA,2022-01-19 23:50:08
7,7,Mataura,-46.1927,168.8643,56.48,80,99,8.84,NZ,2022-01-19 23:50:09
8,8,Jamestown,-15.9387,-5.7168,70.02,77,0,13.40,SH,2022-01-19 23:50:09
9,9,Vaini,-21.2000,-175.2000,82.04,82,4,19.19,TO,2022-01-19 23:50:09

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID       628
City          628
Lat           628
Lng           628
Max Temp      628
Humidity      628
Cloudiness    628
Wind Speed    628
Country       622
Date          628
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
preferred_cities_df = preferred_cities_df.dropna()
preferred_cities_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Ixtapa,20.7000,-105.2000,75.22,89,100,5.01,MX,2022-01-19 23:50:07
1,1,Karaton,-6.3424,106.1045,79.95,93,97,5.17,ID,2022-01-19 23:50:07
2,2,Ushuaia,-54.8000,-68.3000,53.26,58,0,17.27,AR,2022-01-19 23:45:13
3,3,Busselton,-33.6500,115.3333,78.04,52,2,9.98,AU,2022-01-19 23:50:08
4,4,Pacific Grove,36.6177,-121.9166,65.43,75,0,1.01,US,2022-01-19 23:50:08
...,...,...,...,...,...,...,...,...,...,...
711,711,Mount Isa,-20.7333,139.5000,78.57,89,40,4.61,AU,2022-01-20 00:07:54
712,712,Muros,42.7762,-9.0603,51.24,85,2,9.80,ES,2022-01-20 00:07:54
713,713,Grand-Santi,4.2500,-54.3833,72.34,99,73,2.48,GF,2022-01-20 00:07:54
714,714,Daru,-9.0763,143.2092,78.58,89,95,7.90,PG,2022-01-20 00:07:55
715,715,Maumere,-8.6199,122.2111,77.79,85,100,5.68,ID,2022-01-20 00:07:55

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df.copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df["Hotel Rating"] = ""
hotel_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Rating
0,0,Ixtapa,20.7000,-105.2000,75.22,89,100,5.01,MX,2022-01-19 23:50:07,,
1,1,Karaton,-6.3424,106.1045,79.95,93,97,5.17,ID,2022-01-19 23:50:07,,
2,2,Ushuaia,-54.8000,-68.3000,53.26,58,0,17.27,AR,2022-01-19 23:45:13,,
3,3,Busselton,-33.6500,115.3333,78.04,52,2,9.98,AU,2022-01-19 23:50:08,,
4,4,Pacific Grove,36.6177,-121.9166,65.43,75,0,1.01,US,2022-01-19 23:50:08,,
5,5,Venado Tuerto,-33.7456,-61.9688,76.78,83,98,2.55,AR,2022-01-19 23:50:08,,
6,6,Bredasdorp,-34.5322,20.0403,66.27,88,27,6.91,ZA,2022-01-19 23:50:08,,
7,7,Mataura,-46.1927,168.8643,56.48,80,99,8.84,NZ,2022-01-19 23:50:09,,
8,8,Jamestown,-15.9387,-5.7168,70.02,77,0,13.40,SH,2022-01-19 23:50:09,,
9,9,Vaini,-21.2000,-175.2000,82.04,82,4,19.19,TO,2022-01-19 23:50:09,,

In [9]:
import json
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
skipcount = 0
noratingscount = 0

for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    # Grab the first hotel from the results and store the name.
    try:
        #print(json.dumps(hotels["results"][0], indent = 4))
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        hotel_df.loc[index, "Hotel Rating"] = hotels["results"][0]["rating"]
    except (IndexError):
        print("Hotel not found... skipping.")
        skipcount+=1
    except (KeyError):
        print("Hotel has no Ratings... skipping.")
        skipcount+=1
        noratingscount+=1
print(f"Found {len(hotel_df)} Hotels after skipping {skipcount}, of which {noratingscount} were due to lack of a rating.")
hotel_df

Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel not found... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Hotel has no Ratings... skipping.
Found 622 Hotels after skipping 116, of which 60 were due to lack of a rating.

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Rating
0,0,Ixtapa,20.7000,-105.2000,75.22,89,100,5.01,MX,2022-01-19 23:50:07,Hotel Plaza Providencia,4.4
1,1,Karaton,-6.3424,106.1045,79.95,93,97,5.17,ID,2022-01-19 23:50:07,Parkir Mobil Wisata CAS Water Park,4.3
2,2,Ushuaia,-54.8000,-68.3000,53.26,58,0,17.27,AR,2022-01-19 23:45:13,Albatross Hotel,4.3
3,3,Busselton,-33.6500,115.3333,78.04,52,2,9.98,AU,2022-01-19 23:50:08,Observatory Guest House,4.5
4,4,Pacific Grove,36.6177,-121.9166,65.43,75,0,1.01,US,2022-01-19 23:50:08,Lovers Point Inn,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...
711,711,Mount Isa,-20.7333,139.5000,78.57,89,40,4.61,AU,2022-01-20 00:07:54,ibis Styles Mt Isa Verona,3.9
712,712,Muros,42.7762,-9.0603,51.24,85,2,9.80,ES,2022-01-20 00:07:54,Apartment Av. Castelao,
713,713,Grand-Santi,4.2500,-54.3833,72.34,99,73,2.48,GF,2022-01-20 00:07:54,Hotel La Villa Couacou,3
714,714,Daru,-9.0763,143.2092,78.58,89,95,7.90,PG,2022-01-20 00:07:55,Daru Lodge,
715,715,Maumere,-8.6199,122.2111,77.79,85,100,5.68,ID,2022-01-20 00:07:55,Sylvia Hotel,4.1

In [10]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.dropna()
hotel_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name,Hotel Rating
0,0,Ixtapa,20.7000,-105.2000,75.22,89,100,5.01,MX,2022-01-19 23:50:07,Hotel Plaza Providencia,4.4
1,1,Karaton,-6.3424,106.1045,79.95,93,97,5.17,ID,2022-01-19 23:50:07,Parkir Mobil Wisata CAS Water Park,4.3
2,2,Ushuaia,-54.8000,-68.3000,53.26,58,0,17.27,AR,2022-01-19 23:45:13,Albatross Hotel,4.3
3,3,Busselton,-33.6500,115.3333,78.04,52,2,9.98,AU,2022-01-19 23:50:08,Observatory Guest House,4.5
4,4,Pacific Grove,36.6177,-121.9166,65.43,75,0,1.01,US,2022-01-19 23:50:08,Lovers Point Inn,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...
711,711,Mount Isa,-20.7333,139.5000,78.57,89,40,4.61,AU,2022-01-20 00:07:54,ibis Styles Mt Isa Verona,3.9
712,712,Muros,42.7762,-9.0603,51.24,85,2,9.80,ES,2022-01-20 00:07:54,Apartment Av. Castelao,
713,713,Grand-Santi,4.2500,-54.3833,72.34,99,73,2.48,GF,2022-01-20 00:07:54,Hotel La Villa Couacou,3
714,714,Daru,-9.0763,143.2092,78.58,89,95,7.90,PG,2022-01-20 00:07:55,Daru Lodge,
715,715,Maumere,-8.6199,122.2111,77.79,85,100,5.68,ID,2022-01-20 00:07:55,Sylvia Hotel,4.1

In [11]:
#dfi.export(hotel_df, "hotel_df.png")

# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [12]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>Rating</dt><dd>{Hotel Rating}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))